version: "3.9"

services:
  php:
    build: .
    working_dir: /app
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - RUNNING_IN_DOCKER=true
    restart: no
    command: php _compiler/server.php
